import { memo, useEffect, useRef, useState, type CSSProperties } from 'react';
import type { NoteRange } from '../useReadingNotes';
import type { Highlight } from './state';
type Paragraph={id:string;text:string;label:string};
export type Evidence={paragraphId:string;text:string};
type Selection={ranges:{paragraphId:string;start:number;end:number}[];text:string;x:number;y:number};
type Props={title:string;subtitle:string;sourceLabel:string;paragraphs:Paragraph[];highlights:Highlight[];onHighlights:(h:Highlight[])=>void|Promise<void>;onSaveNote?:(ranges:NoteRange[],note:string)=>Promise<void>;evidence:Evidence|null;evidenceTick:number;initialScroll:number;onScroll:(y:number)=>void;fontSize:number;onFont:(size:number)=>void;onMessage:(text:string)=>void};
export const PassageReader=memo(function PassageReader({title,subtitle,sourceLabel,paragraphs,highlights,onHighlights,onSaveNote,evidence,evidenceTick,initialScroll,onScroll,fontSize,onFont,onMessage}:Props){
  const [saving,setSaving]=useState(false);const [noteSelection,setNoteSelection]=useState<Selection|null>(null);const [noteText,setNoteText]=useState('');
  const reader=useRef<HTMLDivElement>(null);const toolbar=useRef<HTMLDivElement>(null);const [selection,setSelection]=useState<Selection|null>(null);
  useEffect(()=>{if(reader.current)reader.current.scrollTop=initialScroll;},[]);
  useEffect(()=>{if(!evidence)return;requestAnimationFrame(()=>{const p=reader.current?.querySelector<HTMLElement>(`[data-paragraph="${evidence.paragraphId}"]`);if(p&&reader.current)reader.current.scrollTo({top:p.getBoundingClientRect().top-reader.current.getBoundingClientRect().top+reader.current.scrollTop-32,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});},[evidence,evidenceTick]);
  useEffect(()=>{const select=()=>{const s=window.getSelection();if(!s?.rangeCount||s.isCollapsed){if(!toolbar.current?.contains(document.activeElement))setSelection(null);return;}const range=s.getRangeAt(0);const node=(n:Node)=>n.nodeType===1?n as Element:n.parentElement;const first=node(range.startContainer)?.closest<HTMLElement>('[data-paragraph]');const last=node(range.endContainer)?.closest<HTMLElement>('[data-paragraph]');if(!first||!last||!reader.current?.contains(first)||!reader.current.contains(last)){setSelection(null);return;}
    const elements=[...reader.current.querySelectorAll<HTMLElement>('[data-paragraph]')];const ranges=elements.slice(elements.indexOf(first),elements.indexOf(last)+1).map(p=>{let start=0,end=p.textContent?.length??0;const prefix=range.cloneRange();prefix.selectNodeContents(p);if(p===first){prefix.setEnd(range.startContainer,range.startOffset);start=prefix.toString().length;}if(p===last){prefix.selectNodeContents(p);prefix.setEnd(range.endContainer,range.endOffset);end=prefix.toString().length;}return {paragraphId:p.dataset.paragraph!,start,end};}).filter(r=>r.end>r.start);const rect=range.getBoundingClientRect();
    setSelection({ranges,text:range.toString(),x:Math.max(12,Math.min(rect.left,innerWidth-290)),y:Math.max(72,Math.min(rect.bottom+8,innerHeight-64))});};
    const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelection(null);};document.addEventListener('selectionchange',select);document.addEventListener('keydown',key);return()=>{document.removeEventListener('selectionchange',select);document.removeEventListener('keydown',key);};},[]);
  const finish=()=>{setSelection(null);window.getSelection()?.removeAllRanges();reader.current?.focus({preventScroll:true});};
  const render=(p:Paragraph)=>{const personal=highlights.filter(h=>h.paragraphId===p.id);const at=evidence?.paragraphId===p.id?p.text.indexOf(evidence.text):-1;const cuts=new Set([0,p.text.length]);personal.forEach(h=>{cuts.add(h.start);cuts.add(h.end);});if(at>=0&&evidence){cuts.add(at);cuts.add(at+evidence.text.length);}const positions=[...cuts].sort((a,b)=>a-b);return positions.slice(0,-1).map((start,i)=>{const end=positions[i+1];const user=personal.some(h=>h.start<end&&h.end>start);const ev=at>=0&&!!evidence&&start<at+evidence.text.length&&end>at;return <span key={start} className={`${user?'personal-highlight':''} ${ev?'evidence-highlight':''}`}>{p.text.slice(start,end)}</span>;});};
  return <section className="rp-passage" aria-label="文章阅读区"><div className="rp-reader-tools"><span>PASSAGE 01 <span className="rp-dot">·</span> {sourceLabel}</span><div><button aria-label="缩小字号" disabled={fontSize<=17} onClick={()=>onFont(fontSize-1)}>A−</button><button aria-label="放大字号" disabled={fontSize>=26} onClick={()=>onFont(fontSize+1)}>A+</button></div></div>
    <div ref={reader} className="rp-reader-scroll" tabIndex={0} aria-label="阅读正文" onScroll={e=>{onScroll(e.currentTarget.scrollTop);if(!toolbar.current?.contains(document.activeElement))setSelection(null);}} style={{'--reading-size':`${fontSize}px`} as CSSProperties}>
      <article lang="en"><p className="rp-eyebrow">{subtitle} <span> / </span> {Math.ceil(paragraphs.reduce((n,p)=>n+p.text.split(/\s+/).length,0)/100)} MIN READ</p><h1>{title}</h1>{sourceLabel==='原创练习'&&<p className="rp-deck">A place to pause can change the way we move through a neighbourhood.</p>}<div className="rp-article-rule"/>
        {paragraphs.map(p=><div className={`rp-paragraph ${evidence?.paragraphId===p.id?'is-evidence':''}`} key={p.id}><span className="rp-paragraph-number" aria-hidden="true">{p.label}</span><p data-paragraph={p.id}>{render(p)}</p></div>)}
        <footer className="rp-source">END OF PASSAGE <p>{sourceLabel==='原创练习'?'原创交互测试材料 · 非六级真题':'正式会话快照 · 题库内容保持原样'}<br/>选取原文可高亮、移除标注或复制。</p></footer>
      </article>
    </div>
    {selection&&<div className="rp-selection-tools" ref={toolbar} role="toolbar" aria-label="所选原文操作" style={{left:selection.x,top:selection.y}} onPointerDown={e=>e.preventDefault()}><button disabled={saving} onClick={async()=>{setSaving(true);try{await onHighlights([...highlights,...selection.ranges.map(r=>({...r,id:crypto.randomUUID()}))]);onMessage(onSaveNote?'摘录已保存，提交后显示高亮':'已高亮所选原文');finish();}catch(e){onMessage(e instanceof Error?e.message:'笔记保存失败，请重试');}finally{setSaving(false);}}}>{saving?'保存中…':'高亮'}</button>{onSaveNote&&<button disabled={saving} onClick={()=>{setNoteSelection(selection);setNoteText('');finish();}}>写笔记</button>}<button disabled={saving||!highlights.some(h=>selection.ranges.some(r=>h.paragraphId===r.paragraphId&&h.start<r.end&&h.end>r.start))} title={onSaveNote?'同时移除笔记中的对应摘录':'移除高亮'} onClick={async()=>{setSaving(true);try{await onHighlights(highlights.filter(h=>!selection.ranges.some(r=>h.paragraphId===r.paragraphId&&h.start<r.end&&h.end>r.start)));onMessage(onSaveNote?'已移除高亮及对应摘录':'已移除相交高亮');finish();}catch(e){onMessage(e instanceof Error?e.message:'移除失败');}finally{setSaving(false);}}}>{onSaveNote?'移除高亮及笔记':'移除高亮'}</button><button onClick={async()=>{try{await navigator.clipboard.writeText(selection.text);onMessage('原文已复制');}catch{onMessage('复制失败，请使用系统复制');}finish();}}>复制</button><button aria-label="关闭选择工具" onClick={finish}>关闭</button></div>}
    {noteSelection&&<div className="rp-note-dialog" role="dialog" aria-modal="true" aria-label="保存阅读笔记"><h2>留下这一句</h2><blockquote>{noteSelection.text}</blockquote><textarea autoFocus aria-label="笔记内容" value={noteText} maxLength={5000} onChange={e=>setNoteText(e.target.value)} placeholder="写下你的理解或疑问（可选）"/><div><button disabled={saving} onClick={()=>setNoteSelection(null)}>取消</button><button disabled={saving} onClick={async()=>{setSaving(true);try{await onSaveNote?.(noteSelection.ranges,noteText);setNoteSelection(null);onMessage('笔记已保存');}catch(e){onMessage(e instanceof Error?e.message:'保存失败，请重试');}finally{setSaving(false);}}}>{saving?'保存中…':'保存笔记'}</button></div></div>}
  </section>;
});
