import type { KeyboardEvent } from 'react';
import type { ReadingQuestionReview } from './types';
type Question={id:string;number:number;stem:string;options:{key:string;text:string}[]};
export function QuestionProgress({answered,total,review}:{answered:number;total:number;review:boolean}){return <div className="rp-progress"><span>{review?'本轮已完成':'答题进度'}</span><strong>{answered}<span> / {total}</span></strong><progress value={answered} max={total} aria-label="已回答题数"/></div>;}
export function QuestionNavigator({questions,current,answers,flagged,reviews,onMove}:{questions:Question[];current:string;answers:Record<string,string>;flagged:string[];reviews:ReadingQuestionReview[]|null;onMove:(id:string)=>void}){return <nav className="rp-question-nav" aria-label="题号导航">{questions.map(q=>{const r=reviews?.find(r=>r.questionId===q.id);const state=r?(answers[q.id]===r.correctOptionId?'正确':answers[q.id]?'错误':'未作答'):answers[q.id]?'已作答':'未作答';return <button key={q.id} aria-current={current===q.id?'step':undefined} aria-label={`第 ${q.number} 题，${state}${flagged.includes(q.id)?'，已标记':''}`} className={`${answers[q.id]?'is-answered':''} ${r?(answers[q.id]===r.correctOptionId?'is-correct':'is-wrong'):''}`} onClick={()=>onMove(q.id)}><span>{q.number}</span><small>{flagged.includes(q.id)?'标记':r?state:answers[q.id]?'已答':'待答'}</small></button>;})}</nav>;}
export function QuestionOption({option,selected,locked,correct,wrong,onSelect}:{option:{key:string;text:string};selected:boolean;locked:boolean;correct:boolean;wrong:boolean;onSelect:()=>void}){return <label className={`rp-option ${selected?'is-selected':''} ${correct?'is-correct':''} ${wrong?'is-wrong':''}`}><input type="radio" name="reading-answer" value={option.key} checked={selected} disabled={locked} onChange={onSelect}/><span className="rp-option-letter">{option.key}</span><span lang="en">{option.text}{correct&&<small>正确答案</small>}{wrong&&<small>我的答案 · 错误</small>}</span></label>;}
export function EvidenceLink({review,index,onEvidence}:{review:ReadingQuestionReview;index:number;onEvidence:(index:number)=>void}){return <section className="rp-evidence-action"><p className="rp-eyebrow">BACK TO THE TEXT</p>{review.evidence.length?<><button className="rp-primary" onClick={()=>onEvidence(index%review.evidence.length)}>查看原文证据 <span aria-hidden="true">↗</span></button>{review.evidence.length>1&&<div className="rp-evidence-switch" aria-label="证据位置">{review.evidence.map((_,i)=><button key={i} aria-pressed={index===i} onClick={()=>onEvidence(i)}>证据 {i+1}</button>)}</div>}</>:<p className="rp-muted">当前题目暂无精确证据定位</p>}</section>;}
export function ReadingReviewPanel({question,answer,review,index,onEvidence}:{question:Question;answer?:string;review:ReadingQuestionReview;index:number;onEvidence:(index:number)=>void}){return <section className="rp-review" aria-label="题目复盘"><div className="rp-review-result"><strong>{answer===review.correctOptionId?'回答正确':answer?'回答错误':'未作答'}</strong><span>我的答案 {answer??'—'} <span aria-hidden="true"> / </span> 正确答案 {review.correctOptionId}</span></div><EvidenceLink review={review} index={index} onEvidence={onEvidence}/><h3>解题逻辑</h3><p>{review.explanation}</p><details key={question.id}><summary>错误选项分析</summary>{Object.entries(review.distractorExplanations).map(([key,text])=><p key={key}><strong>{key}</strong> · {text}</p>)}</details></section>;}
export function QuestionPanel({question,answer,flagged,review,reviewIndex,onAnswer,onFlag,onEvidence,locked=false}:{question:Question;answer?:string;flagged:boolean;review:ReadingQuestionReview|null;reviewIndex:number;onAnswer:(key:string)=>void;onFlag:()=>void;onEvidence:(index:number)=>void;locked?:boolean}){
  const keyboard=(e:KeyboardEvent<HTMLDivElement>)=>{if(review||locked)return;const n=question.options.findIndex(o=>o.key===answer);if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();const next=(n+(e.key==='ArrowDown'||e.key==='ArrowRight'?1:3)+4)%4;onAnswer(question.options[next].key);e.currentTarget.querySelectorAll<HTMLInputElement>('input')[next]?.focus();}};
  return <><div className="rp-question-kicker"><p className="rp-eyebrow">QUESTION {question.number} <span> / </span> 单项选择</p><button className={`rp-flag ${flagged?'is-flagged':''}`} aria-pressed={flagged} onClick={onFlag}>{flagged?'已标记':'标记此题'}</button></div><h2 lang="en">{question.stem}</h2><div className="rp-options" role="radiogroup" aria-label={`第 ${question.number} 题选项`} onKeyDown={keyboard}>{question.options.map(o=><QuestionOption key={o.key} option={o} selected={answer===o.key} locked={!!review||locked} correct={!!review&&o.key===review.correctOptionId} wrong={!!review&&answer===o.key&&answer!==review.correctOptionId} onSelect={()=>onAnswer(o.key)}/>)}</div>{review?<ReadingReviewPanel question={question} answer={answer} review={review} index={reviewIndex} onEvidence={onEvidence}/>:<p className="rp-answer-hint">可以随时修改选择。提交后，回到原文理解答案。</p>}</>;
}
