import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import fixture from './fixture.generated';
import { initialState, restoreState, prototypeStorageKey, type PracticeState } from './state';
import { PassageReader, type Evidence } from './PassageReader';
import { QuestionNavigator, QuestionPanel, QuestionProgress } from './QuestionPanel';
import type { ReadingQuestionReview } from './types';
import './reading.css';
import { readTheme, saveTheme } from '../theme';
export type WorkspaceData={id:string;title:string;subtitle:string;paragraphs:{id:string;label:string;text:string;position:number}[];questions:{id:string;number:number;stem:string;options:{key:string;text:string}[];paragraph_ids:string[]}[]};
export type ReadingConnection={practiceLabel?:string;data:WorkspaceData;storageKey:string;answers:Record<string,string>;flags:string[];cursor:number;scroll:number;reviews:ReadingQuestionReview[]|null;saveLabel:string;blocked:boolean;onAnswer:(id:string,key:string)=>void;onFlag:(id:string)=>void;onMove:(index:number)=>void;onScroll:(y:number)=>void;submit:()=>Promise<void>;leave?:()=>Promise<void>;retry?:()=>Promise<void>};
export default function ReadingPlayground(){return <ReadingWorkspace/>;}
export function ReadingWorkspace({connection}:{connection?:ReadingConnection}){
  const data=connection?.data??fixture;const questionIds=data.questions.map(q=>q.id);const storageKey=connection?.storageKey??prototypeStorageKey;
  const [localState,setState]=useState<PracticeState>(()=>{const base=initialState(data.id,questionIds[0]);try{return {...restoreState(localStorage.getItem(storageKey),base,data.questions,data.paragraphs),theme:readTheme()};}catch{return base;}});
  const state=connection?{...localState,selectedAnswers:connection.answers,flaggedQuestionIds:connection.flags,currentQuestionId:questionIds[connection.cursor]??questionIds[0],readerScrollPosition:connection.scroll,practiceStatus:connection.reviews?'review' as const:'practice' as const}:localState;
  const current=useRef(state);current.current=state;const initialReaderScroll=useRef(state.readerScrollPosition);
  const [mockReviews,setReviews]=useState<ReadingQuestionReview[]|null>(null);const reviews=connection?connection.reviews:mockReviews;const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState(false);const [message,setMessage]=useState('');const [saveError,setSaveError]=useState(false);
  const [evidence,setEvidence]=useState<Evidence|null>(null);const [evidenceTick,setEvidenceTick]=useState(0);const [showReturn,setShowReturn]=useState(false);
  const questionScroll=useRef<HTMLDivElement>(null);const workspace=useRef<HTMLDivElement>(null);const dialog=useRef<HTMLDialogElement>(null);const submitButton=useRef<HTMLButtonElement>(null);const drag=useRef<{startY:number;state:PracticeState['drawerState']}|null>(null);const submitting=useRef(false);const dragged=useRef(false);
  const update=useCallback((patch:Partial<PracticeState>)=>setState(s=>({...s,...patch})),[]);
  useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(localState));setSaveError(false);}catch{setSaveError(true);}},[localState,storageKey]);
  useEffect(()=>{if(!connection&&state.practiceStatus==='review')void import('./review.mock.generated').then(m=>setReviews(m.default));},[state.practiceStatus,connection]);
  useEffect(()=>{if(confirm){dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();submitButton.current?.focus();}},[confirm]);
  useEffect(()=>{if(questionScroll.current)questionScroll.current.scrollTop=current.current.questionScrollPositions[state.currentQuestionId]??0;},[state.currentQuestionId]);
  useEffect(()=>{if(!message)return;const id=setTimeout(()=>setMessage(''),3500);return()=>clearTimeout(id);},[message]);
  const q=data.questions.find(q=>q.id===state.currentQuestionId)!;const index=questionIds.indexOf(q.id);const total=data.questions.length;const answered=Object.keys(state.selectedAnswers).length;const unanswered=data.questions.length-answered;
  const review=reviews?.find(r=>r.questionId===q.id)??null;const score=reviews?.filter(r=>state.selectedAnswers[r.questionId]===r.correctOptionId).length;
  const move=(id:string)=>{setState(s=>({...s,currentQuestionId:id,reviewSelection:0,questionScrollPositions:{...s.questionScrollPositions,[state.currentQuestionId]:questionScroll.current?.scrollTop??0}}));connection?.onMove(questionIds.indexOf(id));setEvidence(null);setShowReturn(false);};
  const submit=async()=>{if(submitting.current||current.current.practiceStatus==='review')return;submitting.current=true;setBusy(true);try{if(connection){await connection.submit();}else{const m=await import('./review.mock.generated');setReviews(m.default);}update({practiceStatus:'review',drawerState:'full'});setConfirm(false);setMessage(connection?'本轮成绩已由服务端保存':'练习已提交 · 本地模拟判分，未写入学习记录');}catch(e){setMessage(e instanceof Error?e.message:'提交失败，请重试');}finally{submitting.current=false;setBusy(false);}};
  const evidenceJump=(n:number)=>{const ev=review?.evidence[n];if(!ev)return;update({reviewSelection:n,drawerState:'collapsed',tabletView:'passage'});setEvidence(ev);setShowReturn(true);setEvidenceTick(t=>t+1);setMessage(`已定位证据 ${n+1}，段落 ${data.paragraphs.find(p=>p.id===ev.paragraphId)?.label}`);};
  const returnToQuestion=()=>{update({drawerState:'full',tabletView:'questions'});setShowReturn(false);};
  const onHighlights=useCallback((readingHighlights:PracticeState['readingHighlights'])=>update({readingHighlights}),[update]);
  const scrollHandler=useRef(connection?.onScroll);scrollHandler.current=connection?.onScroll;
  const onScroll=useCallback((readerScrollPosition:number)=>{if(scrollHandler.current)scrollHandler.current(readerScrollPosition);else update({readerScrollPosition});},[update]);const onFont=useCallback((fontSize:number)=>update({fontSize}),[update]);
  return <main className="reading-prototype" data-theme={state.theme} style={{'--passage-width':`${state.split}%`} as CSSProperties}>
    <header className="rp-header"><a href="/" className="rp-brand" onClick={e=>{if(connection?.leave){e.preventDefault();void connection.leave().catch(error=>setMessage(error instanceof Error?error.message:"保存失败，请重试"));}}}>CET6 <span>Daily</span></a><div className="rp-breadcrumb"><span>/</span> Reading <span>/</span><span>{state.practiceStatus==='review'?'本轮复盘':'每日阅读练习'}</span></div><div className="rp-header-actions"><span className="rp-save">{saveError?'本地保存失败':connection?.saveLabel??'本地原型 · 自动保存'}</span><button aria-label={state.theme==='light'?'切换深色模式':'切换浅色模式'} onClick={()=>{const theme=state.theme==='light'?'dark':'light';saveTheme(theme);update({theme});}}>{state.theme==='light'?'深色':'浅色'}</button></div></header>
    <div className="rp-mobile-context"><span>{state.practiceStatus==='review'?`复盘 · ${score??'…'}/${total} 正确`:(connection?`仔细阅读 · ${connection.practiceLabel??'正式练习'}`:'仔细阅读 · 原创练习')}</span><span>{answered}/{total} 已答</span></div>
    <div className="rp-tablet-tabs" role="tablist" aria-label="阅读工作区"><button role="tab" aria-selected={state.tabletView==='passage'} onClick={()=>update({tabletView:'passage'})}>文章</button><button role="tab" aria-selected={state.tabletView==='questions'} onClick={()=>update({tabletView:'questions'})}>题目 · {q.number}</button></div>
    <div ref={workspace} className={`rp-workspace view-${state.tabletView} drawer-${state.drawerState}`}>
      <PassageReader sourceLabel={connection?connection.practiceLabel??'正式练习':'原创练习'} title={data.title} subtitle={data.subtitle} paragraphs={data.paragraphs} highlights={state.readingHighlights} onHighlights={onHighlights} evidence={evidence} evidenceTick={evidenceTick} initialScroll={initialReaderScroll.current} onScroll={onScroll} fontSize={state.fontSize} onFont={onFont} onMessage={setMessage}/>
      <div className="rp-separator" role="separator" aria-label="调整文章宽度，双击恢复默认" aria-orientation="vertical" aria-valuemin={40} aria-valuemax={65} aria-valuenow={state.split} tabIndex={0} onDoubleClick={()=>update({split:55})} onKeyDown={e=>{if(e.key==='Home'){e.preventDefault();update({split:55});}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();update({split:Math.max(40,Math.min(65,state.split+(e.key==='ArrowRight'?1:-1)))});}}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId)||!workspace.current)return;const rect=workspace.current.getBoundingClientRect();update({split:Math.max(40,Math.min(65,100*(e.clientX-rect.left)/rect.width))});}} onPointerUp={e=>e.currentTarget.releasePointerCapture(e.pointerId)}><span/></div>
      <section className="rp-questions" aria-label="题目工作区">
        <div className="rp-drawer-control" onPointerDown={e=>{if((e.target as Element).closest('button')?.getAttribute('data-handle')!=='true')return;e.currentTarget.setPointerCapture(e.pointerId);dragged.current=false;drag.current={startY:e.clientY,state:state.drawerState};}} onPointerUp={e=>{if(!drag.current)return;const diff=e.clientY-drag.current.startY;if(Math.abs(diff)>35){dragged.current=true;const levels=['collapsed','half','full'] as const;update({drawerState:levels[Math.max(0,Math.min(2,levels.indexOf(drag.current.state)+(diff<0?1:-1)))]});}drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
          <button data-handle="true" className="rp-drawer-handle" aria-label="展开或收起题目抽屉" aria-expanded={state.drawerState!=='collapsed'} onClick={()=>{if(dragged.current){dragged.current=false;return;}update({drawerState:state.drawerState==='collapsed'?'half':state.drawerState==='half'?'full':'collapsed'});}}><span className="rp-grip"/><span>题目 {q.number} <small>{answered}/{total} 已答</small></span><span>{state.drawerState==='collapsed'?'展开':'收起 / 展开'}</span></button>
          <div className="rp-drawer-levels" aria-label="抽屉高度">{(['collapsed','half','full'] as const).map((level,i)=><button key={level} aria-pressed={state.drawerState===level} onClick={()=>update({drawerState:level})}>{['收起','半屏','全屏'][i]}</button>)}</div>
        </div>
        <div className="rp-question-top"><div className="rp-workspace-title"><p className="rp-eyebrow">{state.practiceStatus==='review'?'READ. REFLECT. UNDERSTAND.':'A LITTLE FOCUS, EVERY DAY.'}</p><span>{state.practiceStatus==='review'?`复盘 · ${score??'…'}/${total} 正确`:'仔细阅读'}</span></div><QuestionProgress answered={answered} total={total} review={state.practiceStatus==='review'}/><QuestionNavigator questions={data.questions} current={q.id} answers={state.selectedAnswers} flagged={state.flaggedQuestionIds} reviews={reviews} onMove={move}/></div>
        <div ref={questionScroll} className="rp-question-scroll" onScroll={e=>{const y=e.currentTarget.scrollTop;setState(s=>({...s,questionScrollPositions:{...s.questionScrollPositions,[state.currentQuestionId]:y}}));}}>
          {state.practiceStatus==='review'&&!review?<p role="status">正在加载本地复盘…</p>:<QuestionPanel locked={busy||connection?.blocked} question={q} answer={state.selectedAnswers[q.id]} flagged={state.flaggedQuestionIds.includes(q.id)} review={review} reviewIndex={state.reviewSelection} onAnswer={key=>{if(connection){if(!connection.blocked)connection.onAnswer(q.id,key);return;}if(current.current.practiceStatus==='practice')setState(s=>({...s,selectedAnswers:{...s.selectedAnswers,[q.id]:key}}));}} onFlag={()=>{if(connection){connection.onFlag(q.id);return;}update({flaggedQuestionIds:state.flaggedQuestionIds.includes(q.id)?state.flaggedQuestionIds.filter(id=>id!==q.id):[...state.flaggedQuestionIds,q.id]});}} onEvidence={evidenceJump}/>}
          <div className="rp-paging"><button disabled={index===0} onClick={()=>move(questionIds[index-1])}>← 上一题</button><span>{index+1} / {total}</span><button disabled={index>=total-1} onClick={()=>move(questionIds[index+1])}>下一题 →</button></div>
        </div>
        <footer className="rp-submit"><span>{state.practiceStatus==='review'?(connection?'成绩已保存':'本地模拟成绩'):unanswered?`还有 ${unanswered} 题未作答`:'已完成全部题目'}</span>{state.practiceStatus==='practice'?<button ref={submitButton} className="rp-primary" disabled={busy||connection?.blocked} onClick={()=>setConfirm(true)}>提交练习</button>:<button onClick={()=>{if(connection){void connection.retry?.().catch(e=>setMessage(String(e)));return;}setState(s=>({...s,selectedAnswers:{},flaggedQuestionIds:[],currentQuestionId:questionIds[0],practiceStatus:'practice',reviewSelection:0,questionScrollPositions:{},drawerState:'half'}));setReviews(null);setEvidence(null);setShowReturn(false);}}>重新练习</button>}</footer>
      </section>
    </div>
    {showReturn&&<button className="rp-return" onClick={returnToQuestion}>返回题目解析 →</button>}
    <div className="rp-live" role="status" aria-live="polite">{message|| (saveError?'无法保存至本机，刷新可能丢失进度':'')}</div>
    <dialog ref={dialog} className="rp-dialog" onCancel={e=>{e.preventDefault();if(!busy)setConfirm(false);}} aria-labelledby="rp-submit-title"><h2 id="rp-submit-title">{unanswered?`还有 ${unanswered} 题未作答`:'准备好回到原文了吗？'}</h2><p>{unanswered?'可以返回补答，也可以按当前答案提交。未作答题目计为错误。':'提交后锁定本轮答案，查看判分、原文证据及解题逻辑。'}</p><p className="rp-muted">{connection?'正式练习：提交后由服务端判分并保存学习记录。':'这是本地交互原型，不会写入正式学习记录。'}</p><div><button disabled={busy} onClick={()=>setConfirm(false)}>返回检查</button><button className="rp-primary" disabled={busy} onClick={()=>void submit()}>{busy?'判分中…':'确认提交'}</button></div></dialog>
  </main>;
}
