import { useEffect, useRef, useState, type ReactNode } from 'react';
import type { PublicGroup, Session, Result, Choice } from '../shared/contracts';
import { useDraft } from './useDraft';
import { api, friendly } from './api';
import { categories } from './StatsView';
type Props={initial:Session;uid:string;result:Result|null;onLeave:()=>void;onSubmitted:()=>Promise<void>;onRetry:()=>void};
type Evidence={paragraph_id:string;text:string};
export function Reader(props:Props) { return props.result?<ResultReader {...props} result={props.result}/>:<ActiveReader {...props}/>; }
function Layout({group,header,right,initialScroll=0,initialView='passage',onScroll,activeNumber,onBlank,choices,evidence}:{group:PublicGroup;header:ReactNode;right:ReactNode;initialScroll?:number;initialView?:'passage'|'questions';onScroll?:(y:number)=>void;activeNumber?:number;onBlank?:(n:number)=>void;choices?:Record<string,Choice>;evidence?:Evidence|null}) {
  const [view,setView]=useState<'passage'|'questions'>(initialView);const [font,setFont]=useState(19);const passage=useRef<HTMLDivElement>(null);
  const [selection,setSelection]=useState<{paragraph_id:string;text:string}|null>(null);const [note,setNote]=useState('');const [noteKind,setNoteKind]=useState<'note'|'sentence'>('note');const [noteBusy,setNoteBusy]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{if(passage.current)passage.current.scrollTop=initialScroll;},[]);
  useEffect(()=>{ if(evidence) {setView('passage');requestAnimationFrame(()=>{const element=document.getElementById(`paragraph-${evidence.paragraph_id}`);if(element&&passage.current)passage.current.scrollTo({top:element.offsetTop-passage.current.offsetTop-24,behavior:'instant'});});} },[evidence]);
  const select=()=>{
    const s=window.getSelection(); const text=s?.toString().trim();if(!s||!text||!s.rangeCount)return;
    const common=s.getRangeAt(0).commonAncestorContainer;const node=common.nodeType===Node.ELEMENT_NODE?common as Element:common.parentElement;
    const p=node?.closest<HTMLElement>('[data-paragraph]');if(!p||!passage.current?.contains(p))return;
    const source=group.passage.paragraphs.find(row=>row.id===p.dataset.paragraph);
    if(source?.text.includes(text)){setSelection({paragraph_id:source.id,text});setMessage('');setNote('');}
  };
  const renderText=(text:string,pid:string)=>{
    if(evidence?.paragraph_id===pid && text.includes(evidence.text)) {const at=text.indexOf(evidence.text);return <>{text.slice(0,at)}<mark>{evidence.text}</mark>{text.slice(at+evidence.text.length)}</>;}
    if(group.kind!=='cloze')return text;
    return text.split(/(\{\{\d+\}\})/g).map((part,i)=>{
      const n=part.match(/^\{\{(\d+)\}\}$/)?.[1];if(!n)return part;
      const q=group.questions.find(q=>q.number===Number(n));const choice=q&&choices?.[q.id]?.answer;const word=group.passage.word_bank.find(w=>w.key===choice);
      return <button key={i} className={`blank ${activeNumber===Number(n)?'active':''}`} onClick={()=>{onBlank?.(Number(n));setView('questions');}} aria-label={`选择第 ${n} 空`}>{word?word.text:`${n} ____`}</button>;
    });
  };
  return <div className="reader-shell"><header className="reader-header">{header}</header><div className="mobile-switch" role="tablist" aria-label="阅读视图"><button role="tab" aria-selected={view==='passage'} onClick={()=>setView('passage')}>阅读文章</button><button role="tab" aria-selected={view==='questions'} onClick={()=>setView('questions')}>回答题目</button></div>
    <div className={`reader-columns view-${view}`}><section className="passage-side" aria-label="阅读文章"><div className="passage-toolbar"><span>{group.paper.year} 年 {group.paper.month} 月 · 第 {group.paper.set} 套</span><div><label className="sr-only" htmlFor="paragraph-jump">定位段落</label><select id="paragraph-jump" defaultValue="" onChange={e=>{const p=document.getElementById(`paragraph-${e.target.value}`);if(p&&passage.current)passage.current.scrollTop=p.offsetTop-passage.current.offsetTop-24;}}><option value="" disabled>定位段落</option>{group.passage.paragraphs.map(p=><option key={p.id} value={p.id}>段落 {p.label}</option>)}</select><button aria-label="缩小文章字体" disabled={font<=16} onClick={()=>setFont(f=>f-1)}>A−</button><button aria-label="放大文章字体" disabled={font>=26} onClick={()=>setFont(f=>f+1)}>A+</button></div></div>
      <div ref={passage} className="passage-scroll" onScroll={e=>onScroll?.(e.currentTarget.scrollTop)} onMouseUp={select} onTouchEnd={select} style={{fontSize:font}}><div className="article-title"><p className="reading-type">{group.kind==='careful'?'Careful Reading':group.kind==='matching'?'Matching':'Word Bank Cloze'}</p><h1>{group.title}</h1></div>{group.passage.paragraphs.map(p=><p className="paragraph" id={`paragraph-${p.id}`} data-paragraph={p.id} key={p.id}><span className="paragraph-label" aria-label={`段落 ${p.label}`}>{p.label}</span>{renderText(p.text,p.id)}</p>)}<p className="source-caption">来源：{group.source.path} · 内容版本 {group.version}</p></div>
    </section><section className="questions-side" aria-label="题目区域">{right}</section></div>
    {selection&&<div className="note-popover" role="dialog" aria-label="保存阅读笔记"><div className="section-title"><h3>留下这一句</h3><button aria-label="关闭笔记" onClick={()=>setSelection(null)}>×</button></div><blockquote>{selection.text}</blockquote><textarea aria-label="笔记内容" value={note} onChange={e=>setNote(e.target.value)} placeholder="写下你的理解或疑问（可选）"/><label className="check-label"><input type="checkbox" checked={noteKind==='sentence'} onChange={e=>setNoteKind(e.target.checked?'sentence':'note')}/>标记为难句</label><div className="button-row"><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(selection.text);setMessage('已复制');}catch{setMessage('复制失败，请使用系统复制');}}}>复制</button><button className="primary" disabled={noteBusy} onClick={async()=>{setNoteBusy(true);try{await api('/annotations','POST',{passage_id:group.passage.id,paragraph_id:selection.paragraph_id,selected_text:selection.text,note,kind:noteKind});setMessage('笔记已保存');}catch(e){setMessage(friendly(e));}finally{setNoteBusy(false);}}}>{noteBusy?'保存中…':'保存笔记'}</button></div><p role="status">{message}</p></div>}
  </div>;
}
function ActiveReader({initial,uid,onLeave,onSubmitted}:Props) {
  const d=useDraft(initial,uid);const group=initial.snapshot;const questions=group.questions.filter(q=>initial.question_ids.includes(q.id));const q=questions[d.draft.cursor]??questions[0];
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [confirm,setConfirm]=useState(false);
  const unanswered=questions.filter(q=>!d.draft.choices[q.id]?.answer).length;
  const saveNames={saved:'已保存',saving:'保存中',failed:'保存失败 · 本机保留',conflict:'草稿冲突'};
  const pause=async()=>{setBusy(true);d.update(s=>({...s,paused:true}));try{await d.flush();onLeave();}catch(e){setError(friendly(e));}finally{setBusy(false);}};
  const submit=async()=>{setBusy(true);setError('');try{await d.submit();await onSubmitted();}catch(e){setError(friendly(e));}finally{setBusy(false);setConfirm(false);}};
  const move=(cursor:number)=>d.update(s=>({...s,cursor}));
  return <Layout group={group} initialScroll={d.draft.scroll} onScroll={scroll=>d.update(s=>({...s,scroll}))} choices={d.draft.choices} activeNumber={q.number} onBlank={n=>{const i=questions.findIndex(q=>q.number===n);if(i>=0)move(i);}}
    header={<><button className="back-button" disabled={busy} onClick={()=>void pause()}>← 今日</button><span className="reader-brand">CET6 Daily</span><div className="session-status"><span className={d.state==='failed'||d.state==='conflict'?'save-error':'save-state'} role="status">{saveNames[d.state]}</span><span className="time-display">{Math.floor(d.draft.elapsed_ms/60000)}:{String(Math.floor(d.draft.elapsed_ms/1000)%60).padStart(2,'0')}</span><button className="text-button" disabled={busy} onClick={()=>void pause()}>暂停并保存</button></div></>}
    right={<><div className="question-nav"><span>{initial.practice_type==='review'?'到期复习':'整篇练习'} · {questions.length-unanswered}/{questions.length}</span><div>{questions.map((item,i)=><button key={item.id} aria-label={`第 ${item.number} 题`} aria-current={i===d.draft.cursor?'step':undefined} className={`${d.draft.choices[item.id]?.answer?'answered':''} ${d.draft.choices[item.id]?.uncertain?'uncertain':''}`} onClick={()=>move(i)}>{item.number}</button>)}</div></div>
      <div className="question-scroll">
        {error&&<div className="error" role="alert">{error}</div>}
        {d.state==='failed'&&<div className="save-warning">草稿仍保留在本机。<button onClick={()=>void d.flush().catch(e=>setError(friendly(e)))}>重新保存</button></div>}
        {d.state==='conflict'&&<div className="save-warning" role="alert"><p>云端存在更新的草稿。为避免覆盖其他设备，请选择：</p><button onClick={()=>void d.resolveConflict(false).catch(e=>setError(friendly(e)))}>使用云端草稿</button><button onClick={()=>void d.resolveConflict(true).catch(e=>setError(friendly(e)))}>保留本机草稿并覆盖云端</button></div>}
        {d.draft.paused&&<div className="pause-notice"><h3>阅读已暂停</h3><p>答案和阅读位置已保留。</p><button className="primary" onClick={()=>d.update(s=>({...s,paused:false}))}>继续阅读</button></div>}
        <p className="question-number">QUESTION {q.number}</p><h2 className="question-stem" lang="en">{q.stem}</h2>
        {group.kind==='careful'?<div className="options">{q.options.map(o=><button key={o.key} disabled={d.draft.paused||busy} className={`option ${d.draft.choices[q.id]?.answer===o.key?'selected':''}`} aria-pressed={d.draft.choices[q.id]?.answer===o.key} onClick={()=>d.answer(q.id,o.key)}><span className="option-key">{o.key}</span><span lang="en">{o.text}</span></button>)}</div>:group.kind==='matching'?<><p className="muted">选择对应段落；多个陈述可以对应同一段落。</p><div className="matching-options">{q.options.map(o=><button key={o.key} disabled={d.draft.paused||busy} aria-pressed={d.draft.choices[q.id]?.answer===o.key} className={d.draft.choices[q.id]?.answer===o.key?'selected':''} onClick={()=>d.answer(q.id,o.key)}>{o.key}</button>)}</div></>:<><p className="muted">为第 {q.number} 空选择词汇。同一词汇仅使用一次。</p><div className="word-bank">{q.options.map(o=>{const used=questions.some(item=>item.id!==q.id && d.draft.choices[item.id]?.answer===o.key);return <button key={o.key} disabled={used||d.draft.paused||busy} className={d.draft.choices[q.id]?.answer===o.key?'selected':''} aria-pressed={d.draft.choices[q.id]?.answer===o.key} onClick={()=>d.answer(q.id,o.key)}><span>{o.key}</span> {o.text}{used&&<small> 已使用</small>}</button>;})}</div><button className="text-button" disabled={d.draft.paused||busy||!d.draft.choices[q.id]?.answer} onClick={()=>d.answer(q.id,null)}>清除本空选择</button></>}
        <label className="check-label"><input type="checkbox" checked={d.draft.choices[q.id]?.uncertain??false} disabled={d.draft.paused||busy} onChange={()=>d.uncertain(q.id)}/>这道题不确定，稍后再看</label>
        <div className="question-paging"><button disabled={d.draft.cursor===0||busy} onClick={()=>move(d.draft.cursor-1)}>← 上一题</button><span>{d.draft.cursor+1} / {questions.length}</span><button disabled={d.draft.cursor>=questions.length-1||busy} onClick={()=>move(d.draft.cursor+1)}>下一题 →</button></div><p className="answer-privacy">整组提交后查看答案与原文证据。</p>
      </div><div className="submit-bar"><span>{unanswered?`还有 ${unanswered} 题未作答`:'已完成全部选择'}</span><button className="primary" disabled={busy||d.state==='conflict'||d.draft.paused} onClick={()=>setConfirm(true)}>{busy?'正在提交…':'提交整组'}</button></div>
      {confirm&&<div className="modal-backdrop"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="submit-title"><h2 id="submit-title">提交本组答案？</h2><p>{unanswered?`仍有 ${unanswered} 道未作答，将按错误计分。`:'提交后保存本轮成绩，并展示答案。'}首轮成绩会永久保留。</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setConfirm(false)}>继续检查</button><button className="primary" disabled={busy} onClick={()=>void submit()}>确认提交</button></div></div></div>}
    </>}/>;
}
function ResultReader({initial,result,onLeave,onRetry}:Props & {result:Result}) {
  const [current,setCurrent]=useState(0);const [show,setShow]=useState(false);const [evidence,setEvidence]=useState<Evidence|null>(null);const [message,setMessage]=useState('');
  const questions=initial.snapshot.questions.filter(q=>initial.question_ids.includes(q.id));const q=questions[current];const a=result.attempts.find(a=>a.question_id===q.id)!;
  const add=async(category?:string)=>{try{await api(`/reviews/${encodeURIComponent(q.id)}`,'POST',category?{error_category:category}:{});setMessage('已加入复习池');}catch(e){setMessage(friendly(e));}};
  return <Layout group={initial.snapshot} initialScroll={initial.scroll} initialView="questions" choices={initial.choices} evidence={evidence}
    header={<><button className="back-button" onClick={onLeave}>← 今日</button><span className="reader-brand">阅读结果</span><span className="quiet-label">本轮成绩已保存</span></>}
    right={<><div className="result-summary"><p>{initial.practice_type==='new'?'首次作答':initial.practice_type==='review'?'错题复习':'重做'}已完成</p><h2><strong>{result.score}</strong><span> / {result.total} 题正确</span></h2><p className="muted">用时 {Math.floor(initial.elapsed_ms/60000)} 分 {Math.floor(initial.elapsed_ms/1000)%60} 秒 · 未作答 {result.attempts.filter(a=>!a.submitted_answer).length} 题</p></div><div className="question-nav"><div>{questions.map((q,i)=>{const a=result.attempts.find(a=>a.question_id===q.id)!;return <button key={q.id} aria-label={`查看第 ${q.number} 题结果`} aria-current={current===i?'step':undefined} className={a.is_correct?'correct':'wrong'} onClick={()=>{setCurrent(i);setShow(false);setMessage('');}}>{q.number}</button>;})}</div></div>
      <div className="question-scroll"><p className="question-number">QUESTION {q.number} · {a.is_correct?'回答正确':'需要复习'}{a.uncertain?' · 不确定':''}</p><h2 className="question-stem">{q.stem}</h2><div className="result-answers"><span>你的答案 <strong>{a.submitted_answer??'未作答'}</strong></span><span>标准答案 <strong>{a.correct_answer}</strong></span></div><div className="result-options">{q.options.map(o=><p key={o.key} className={o.key===a.correct_answer?'correct-text':''}>{o.key}. {o.text}{o.key===a.correct_answer?' ✓':''}</p>)}</div><p className="caption">答案版本 {a.answer_version}</p>
        {!a.is_correct&&<p className="review-note">此题已进入复习池，保留全文上下文。</p>}
        <div className="button-row"><button className="secondary" onClick={()=>setShow(s=>!s)}>{show?'收起解析':'查看解析'}</button><button className="text-button" onClick={()=>void add()}>加入复习</button></div>
        {show&&(a.explanation?<section className="explanation"><h3>从原文找到依据</h3>{a.explanation.evidence.map((ev,i)=><button className="evidence" key={i} onClick={()=>setEvidence({...ev})}><span>段落 {initial.snapshot.passage.paragraphs.find(p=>p.id===ev.paragraph_id)?.label} · 定位原文 ↗</span><q lang="en">{ev.text}</q></button>)}<h4>题干与原文的关系</h4><p>{a.explanation.keyword_relation}</p><h4>正确答案的推导</h4><p>{a.explanation.explanation}</p><h4>其他选项</h4>{Object.entries(a.explanation.distractor_explanations).map(([key,text])=><p key={key}><strong>{key}</strong> · {text}</p>)}<div className="skills">{a.explanation.skill_tags.join(' · ')}</div></section>:<div className="pending-explanation">解析待核验。当前没有可以可靠引用的证据式解析。</div>)}
        <label className="error-category">记录错误原因<select aria-label="错误分类" defaultValue="" key={q.id} onChange={e=>void add(e.target.value)}><option value="" disabled>选择原因（可选）</option>{Object.entries(categories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p role="status">{message}</p>
      </div><div className="submit-bar"><button className="text-button" onClick={onLeave}>返回今日</button><button className="secondary" onClick={onRetry}>重新练习</button></div></>}/>;
}
