import { useEffect, useState } from 'react';
import { api, friendly } from './api';
import type { MistakePage, Stats } from '../shared/contracts';
const percent=(n:number,d:number)=>d?`${Math.round(n/d*100)}%`:'—';
const kinds={careful:'仔细阅读',matching:'匹配 / 新题型',cloze:'选词填空',use_of_english:'完形填空',translation:'翻译',writing:'写作'};
export const categories={vocabulary:'词汇不认识',sentence:'长难句理解错误',locating:'定位错误',inference:'推断错误',distractor:'干扰项误判',time:'时间不足'};
const chinaDay=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function StatsView({stats:s,onOpen}:{stats:Stats;onOpen:(sessionId:string,questionId?:string)=>Promise<void>}) {
  const [day,setDay]=useState(chinaDay);const [page,setPage]=useState<MistakePage|null>(null);const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [opening,setOpening]=useState('');const [reload,setReload]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);setError('');void api<MistakePage>(`/mistakes?day=${day}&offset=${offset}`).then(next=>{if(active)setPage(previous=>offset&&previous?.day===next.day?{...next,items:[...previous.items,...next.items]}:next);}).catch(e=>{if(active)setError(friendly(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[day,offset,reload]);
  const chooseDay=(value:string)=>{setDay(value);setOffset(0);setPage(null);};
  const open=async(sid:string,qid?:string)=>{setOpening(sid+(qid??''));try{await onOpen(sid,qid);}finally{setOpening('');}};
  return <><h1>学习统计</h1><p className="muted">新题看第一次，复习看每一次。日期按北京时间统计。</p><div className="stat-grid"><div className="panel"><span>今日 / 本周题数</span><strong>{s.today_count} / {s.week_count}</strong></div><div className="panel"><span>近 7 天首次正确率</span><strong>{percent(s.first_correct,s.first_count)}</strong></div><div className="panel"><span>复习正确率</span><strong>{percent(s.review_correct,s.review_count)}</strong></div><div className="panel"><span>首次平均作答时间</span><strong>{s.first_count?`${Math.round(s.average_ms/1000)} 秒`:'—'}</strong></div></div>
    <section className="panel stat-section"><h2>首次作答趋势 · 最近 7 天</h2>{s.trend.length?<div className="stats-table-scroll"><table><thead><tr><th>日期</th><th>试卷 / 题型</th><th>完成</th><th>正确率</th><th>记录</th></tr></thead><tbody>{s.trend.map(r=><tr key={r.session_id}><td><button className="text-button" onClick={()=>chooseDay(r.day)} aria-label={`查看 ${r.day} 的错题`}>{r.day}</button></td><td><span>{r.paper.year} 年 {r.paper.month} 月 · 第 {r.paper.set} 套</span><small className="trend-kind">{kinds[r.kind]} · {r.title}</small></td><td>{r.count} 题</td><td>{percent(r.correct,r.count)}</td><td><button className="text-button" disabled={!!opening} onClick={()=>void open(r.session_id)}>查看作答</button></td></tr>)}</tbody></table></div>:<p className="empty">暂无首次作答记录</p>}</section>
    <section className="panel stat-section" aria-label="按日查看错题"><div className="section-title"><h2>每日错题</h2><label className="mistake-date">日期 <input aria-label="错题日期" type="date" value={day} max={chinaDay()} onChange={e=>{if(e.target.value)chooseDay(e.target.value);}}/></label></div><p className="muted">按北京时间查找当天答错或未作答的题目，含首次作答、重做与复习。</p>
      {error&&<p className="error" role="alert">{error}<button onClick={()=>setReload(n=>n+1)}>重新加载错题</button></p>}
      {page?.day===day&&<><p className="caption">{day} · 共 {page.total} 条错题记录</p>{page.items.map(item=><article className="mistake-row" key={item.session_id+item.question_id}><div><p className="caption">{item.paper.year} 年 {item.paper.month} 月 · 第 {item.paper.set} 套 · {kinds[item.kind]} · {item.practice_type==='new'?'首次作答':item.practice_type==='retry'?'重做':'复习'}</p><h3>第 {item.number} 题 · {item.stem}</h3><p className="muted">你的答案 {item.submitted_answer??'未作答'} · 正确答案 {item.correct_answer}</p></div><button className="secondary" disabled={!!opening} onClick={()=>void open(item.session_id,item.question_id)}>{opening===item.session_id+item.question_id?'正在打开…':'查看原文与解析'}</button></article>)}{!page.items.length&&!loading&&<p className="empty">这一天没有错题记录。可切换日期查看。</p>}{page.items.length<page.total&&<button className="text-button" disabled={loading} onClick={()=>setOffset(page.items.length)}>加载更多错题</button>}</>}
      {loading&&<p className="empty" role="status">正在读取错题…</p>}
    </section>
    <div className="two-column"><section className="panel stat-section"><h2>各题型 · 首次作答</h2>{s.by_kind.length?s.by_kind.map(k=><div className="data-row" key={k.kind}><span>{kinds[k.kind]}</span><strong>{percent(k.correct,k.count)} <small>· {k.count} 题</small></strong></div>):<p className="empty">暂无题型记录</p>}</section><section className="panel stat-section"><h2>错误原因</h2>{s.errors.length?s.errors.map(e=><div className="data-row" key={e.category??'none'}><span>{categories[e.category as keyof typeof categories]??'尚未分类'}</span><strong>{e.count}</strong></div>):<p className="empty">暂无错题记录</p>}</section></div>
    <section className="panel stat-section"><h2>真题年份覆盖</h2>{s.by_year.length?s.by_year.map(y=><div className="data-row" key={y.year}><span>{y.year} 年</span><span>{y.count} / {y.total} 道可练习题目</span></div>):<p className="empty">导入已核验题组后开始统计</p>}</section>
    <p className="muted">本周学习 {Math.round(s.week_ms/60000)} 分钟 · 今日已复习 {s.review_completion.completed} 题 · 仍有 {s.review_completion.due} 题到期</p>
  </>;
}
